services:
  telegram_utils_bot:
    container_name: telegram_utils_bot
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    environment:
      - TZ=Africa/Cairo
    env_file:
      - .env
    volumes:
      - ./src:/code/app/src
      - ./pyproject.toml:/code/app/pyproject.toml
      - ./uv.lock:/code/app/uv.lock
      - ./downloads:/code/app/downloads
      - ./tmp:/code/app/tmp
      - ./state:/code/app/state
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - bgutil-provider
    restart: unless-stopped
  bgutil-provider:
    container_name: bgutil-provider
    image: brainicism/bgutil-ytdlp-pot-provider:2.0.0@sha256:ed86b6fdd5e430ddd7c8ce1adb55e1ab54db7c7dbc1bcbf3a82454a85b971164
    ports:
      - "127.0.0.1:4416:4416"
    restart: unless-stopped
